apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    access: proxy
    url: postgres:5432
    user: mlops
    database: mlops_db
    secureJsonData:
      password: 'mlops_password'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
    version: 1
